name: metadata-submission

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda env update --file environment.yml
          $CONDA/bin/conda init bash
          source .bashrc
          $CONDA/bin/conda activate metadata-submission
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7 --show-source --statistics #,F82
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          $CONDA/bin/conda activate metadata-submission
          export PYTHONPATH="$(pwd):scripts/":$PYTHOPATH
          py.test  # test/test_template.py
      - name: Build
        run: |
          $CONDA/bin/conda activate metadata-submission
          export PYTHONPATH="$(pwd):scripts/":$PYTHOPATH
          ./scripts/yaml2emx.py
      - name: Store template
        uses: actions/upload-artifact@v2
        with:
          name: excel-template
          path: templates/sequencing_spreadsheet_template.xlsx